# Generated by Django 5.2.1 on 2025-05-19 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Laboratorio')),
                ('tipo', models.CharField(choices=[('RESISTENCIA', 'Laboratorio de Resistencia de Materiales'), ('INSTRUMENTACION', 'Laboratorio de Instrumentación y Control'), ('METROLOGIA', 'Laboratorio de Metrología'), ('TURBOMAQUINARIA', 'Laboratorio de Turbomaquinaria'), ('HIDRAULICA', 'Laboratorio de Hidráulica')], max_length=20, verbose_name='Tipo de Laboratorio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Número de Cédula')),
                ('codigo_institucional', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Institucional')),
                ('carrera', models.CharField(choices=[('INDUSTRIAL', 'Ingeniería Industrial'), ('MECANICA', 'Ingeniería Mecánica'), ('MANTENIMIENTO', 'Ingeniería en Mantenimiento Industrial'), ('AUTOMOTRIZ', 'Ingeniería Automotriz'), ('PROFESOR', 'Profesor')], max_length=20, verbose_name='Carrera')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Bien')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Bien')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='prestamos.laboratorio', verbose_name='Laboratorio')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion_esperada', models.DateTimeField(verbose_name='Fecha de Devolución Esperada')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('estado', models.CharField(choices=[('PRESTADO', 'Prestado'), ('DEVUELTO', 'Devuelto'), ('RETRASADO', 'Retrasado')], default='PRESTADO', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='prestamos.equipo', verbose_name='Equipo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='prestamos.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
