# Generated by Django 5.2.1 on 2025-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_prestamo_equipo_alter_prestamo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='tipo',
            field=models.CharField(choices=[('LABORATORIO', 'Laboratorio'), ('TALLER', 'Taller')], max_length=20, verbose_name='Tipo de Laboratorio'),
        ),
    ]
